### ISSUE TITLE
Handling missing covariates for detection function fitting

### ISSUE THREAD

**Issue by ericmkeen** [PIFSC-Protected-Species-Division/LTabundR#11]
How to handle missing values in numeric covariates, such as Bft?

Currently `LTabundR` implements an approach in which sightings with missing covariate data are removed from detection function fitting (only if the relevant covariate is specified as a candidate). Then, in abundance estimation, we estimate the ESW for those sightings using the average ESW from the region-year for which density is being estimated.

Is this approach acceptable?

**Comment by amandalbradford** [comment]
While we generally don't want to exclude sightings from the focal survey from detection function estimation, if sightings are just being used for detection function estimation and are missing covariate date, we could just remove them. If we need to retain them for some reason (e.g., from focal survey, although I suspect this would be very uncommon), what about trying to address/interpolate missing covariate values instead of using the average ESW?

**Comment by ericmkeen** [comment]
As noted in this thread [here](https://github.com/PIFSC-Protected-Species-Division/LTabundR/issues/10#issuecomment-2209291776), our new approach to such questions is: never fill in data, but make is easier for users to find and address gaps in data.

Therefore any sightings with missing data in covariate columns that are going to be referenced in detection-function-fitting will be removed from the dataset (both for detection function fitting and abundance estimation). These changes occur within the code for `lta()`. 

Such rows with missing covariates will be flagged in the new function, `lta_checks()`, so that these issues can be fixed if desired before running `lta()` or similar functions.

Change has been applied, working on `lta_checks()` and QAQC now.
